### ISSUE TITLE
Wrong variable used for min_cells in Scrublet

### ISSUE THREAD

**Issue by mvochteloo** [sc-eQTLgen-consortium/WG1-pipeline-QC#17]
In the [scrublet_pipeline.py](https://github.com/sc-eQTLgen-consortium/WG1-pipeline-QC/blob/master/Demultiplexing/scripts/scrublet_pipeline.py) the `scrub_doublets` function  is called using the `min_cells` value as input for `min_counts`.

```
doublet_scores, predicted_doublets = scrub.scrub_doublets(min_counts=args.min_cells, 
                                                          min_cells=args.min_cells, 
                                                          min_gene_variability_pctl=args.min_gene_variability_pctl, 
                                                          n_prin_comps=args.n_prin_comps)
```

Luckily the default for `min_counts` and `min_cells` are identical in [sceQTL-Gen_Demultiplex.yaml](https://github.com/sc-eQTLgen-consortium/WG1-pipeline-QC/blob/master/Demultiplexing/sceQTL-Gen_Demultiplex.yaml) minimising impact:
```
scrublet_extra:
  sim_dbl: 2 ### Number of doublets to simulate relative to the number of observed transcriptomes.
  min_counts: 3 ### Used for gene filtering prior to PCA. Genes expressed at fewer than min_counts in fewer than min_cells are excluded.
  min_cells: 3 ### Used for gene filtering prior to PCA. Genes expressed at fewer than min_counts in fewer than are excluded.")
  n_prin_comps: 30 ### Number of principal components used to embed the transcriptomes priorto k-nearest-neighbor graph construction
```
